pub enum StatField {
    TimeStamp,
    Username,
    Platform,
    PlayLength,
    Country,
    TrackName,
    ArtistName,
    AlbumName,
    ReasonStart,
    ReasonEnd,
    Shuffle,
    Skipped,
}

#[derive(Serialize, Deserialize, Debug)]
pub struct LifeTimeEntry {
    pub ts: String,
    pub username: String,
    pub platform: String,
    pub ms_played: u64,
    pub conn_country: String,
    pub ip_addr_decrypted: String,
    user_agent_decrypted: String,
    pub master_metadata_track_name: Option<String>,
    pub master_metadata_album_artist_name: Option<String>,
    pub master_metadata_album_album_name: Option<String>,
    spotify_track_uri: Option<String>,
    episode_name: Option<String>,
    episode_show_name: Option<String>,
    spotify_episode_uri: Option<String>,
    pub reason_start: String,
    pub reason_end: String,
    pub shuffle: bool,
    pub skipped: Option<bool>,
    offline: bool,
    offline_timestamp: u64,
    incognito_mode: bool,
}
